services:
  postgres:
    image: postgres:latest
    container_name: countries_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - countries_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    container_name: countries_metabase
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - metabase_data:/metabase-data
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db
      MB_JETTY_HOST: 0.0.0.0
      MB_JETTY_PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  countries_postgres_data:
    driver: local
  metabase_data:
    driver: local
